name: Generate Config
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Даем права на запись явно
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Requests
        run: pip install requests

      - name: Run Generator
        run: python generator.py

      - name: Debug - List Files
        run: ls -la # Показывает список файлов, чтобы мы видели ShadowVoice_Live.conf

      - name: Commit and Push Changes
        run: |
          git config --global user.name "PAE16"
          git config --global user.email "action@github.com"
          git add ShadowVoice_Live.conf
          # Проверяем, есть ли изменения, чтобы не падать с ошибкой "nothing to commit"
          if git diff --cached --quiet; then
            echo "Изменений нет, пропускаем коммит."
          else
            git commit -m "Auto-update rules: $(date)"
            git push
          fi
